name: pdfarranger
on:
  push:
    branches: [ win-build ]
  pull_request:
jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: mingw-w64-x86_64-cc 
      - run: /mingw64/bin/python3 --version
      - run: wget http://repo.msys2.org/mingw/mingw64/mingw-w64-x86_64-python-3.8.6-6-any.pkg.tar.zst
      - run: pacman -U mingw-w64-x86_64-python-3.8.6-6-any.pkg.tar.zst --noconfirm
      - run: /mingw64/bin/python3 --version
      - run: pacman -S mingw-w64-x86_64-gtk3 mingw-w64-x86_64-python-gobject mingw-w64-x86_64-python-cairo mingw-w64-x86_64-poppler mingw-w64-x86_64-gcc mingw-w64-x86_64-python-lxml mingw-w64-x86_64-qpdf mingw-w64-x86_64-pybind11 mingw-w64-x86_64-gettext mingw-w64-x86_64-gnutls mingw-w64-x86_64-python-pillow mingw-w64-x86_64-python-dateutil mingw-w64-x86_64-python-pip git python-pip intltool --noconfirm
      - run: /mingw64/bin/python3 -m pip install --user https://launchpad.net/python-distutils-extra/trunk/2.39/+download/python-distutils-extra-2.39.tar.gz
      - run: /mingw64/bin/python3 -m pip install --user keyboard img2pdf pikepdf https://github.com/jeromerobert/cx_Freeze/zipball/pdfarranger
      - run: ./setup.py build 
      - run: /mingw64/bin/python3 setup_win32.py bdist_msi
      - run: /mingw64/bin/python3 setup_win32.py bdist_zip
      - uses: actions/upload-artifact@v2
        with:
          name: pdfarranger-windows-installer-msi
          path: dist/*.msi
      - uses: actions/upload-artifact@v2
        with:
          name: pdfarranger-windows-portable-zip
          path: dist/*.zip
