name: pdfarranger
on:
  push:
    branches: [ win-build ]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    # PikePDF 4.2.0
    container: jeromerobert/pdfarranger-docker-ci:1.4
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: default python
      run: |
         python3 --version
    - name: Install
      run: pip3 install .[image]
    - name: AppStream
      run: appstreamcli validate /usr/share/metainfo/com.github.jeromerobert.pdfarranger.metainfo.xml
    - name: Validate Desktop File
      run: desktop-file-validate /usr/share/applications/com.github.jeromerobert.pdfarranger.desktop
    - name: Tests and Coverage
      run: python3 -X tracemalloc -u -m unittest discover -v -f -s tests
    - name: Codecov
      run: curl -s https://codecov.io/bash | bash
  build-old-pikepdf:
    runs-on: ubuntu-latest
    # PikePDF 1.19
    container: jeromerobert/pdfarranger-docker-ci:1.3.1
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: default python
      run: |
         python3 --version
    - name: Install
      run: pip3 install .[image]
    - name: Tests and Coverage
      run: python3 -X tracemalloc -u -m unittest discover -v -f -s tests
  build-win32:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: default python
      run: |
         python --version
         python3 --version
    - run: python3 setup.py build
    - run: python3 setup_win32.py bdist_msi
    - run: python3 setup_win32.py bdist_zip
    - uses: actions/upload-artifact@v2
      with:
        name: pdfarranger-windows-installer-msi
        path: dist/*.msi
    - uses: actions/upload-artifact@v2
      with:
        name: pdfarranger-windows-portable-zip
        path: dist/*.zip
